version: "2.2"
networks: 
    las2peernet:

services:
    ethereum:
        hostname: ethereum
        networks:
            - las2peernet
        container_name: ethereum
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/monitored-geth-client:master
        command: "/root/start.sh"
        environment:
            GETH_VERBOSITY: 3
            ETHEREUM_DATA_DIR: "/root/.ethereum/devchain"
        ports:
            - "30303"
            - "30303/udp"
            - "8545"
            - "8546"
            - "3000"
        volumes:
            - "ethdata:/root/.ethereum/devchain"

    las2peer-bootstrap:
        hostname: las2peer-bootstrap
        networks:
            - las2peernet
        container_name: las2peer-bootstrap
        depends_on: ["ethereum"]
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/las2peer:master
        environment:
            LAS2PEER_ETH_HOST: "ethereum:8545"
            NODE_ID_SEED: "1"
            LAS2PEER_PORT: "32010"
        ports:
            - "32010:32010"
            - "32010:32010/udp"
            - "32009:8080"
            - "32008:8001"
        volumes:
            - "las2peer-nodestorage:/app/las2peer/node-storage"
        
    mobsos-mysql:
        hostname: mobsos-mysql
        networks:
            - las2peernet
        container_name: mobsos-mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "LAS2PEERMON"
            MYSQL_USER: "root"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306"
        volumes:
            - "mobsos-mysql-data:/var/lib/mysql"

    mobsos-data-processing:
        hostname: mobsos-data-processing
        networks:
            - las2peernet
        container_name: mobsos-data-processing
        depends_on: ["mobsos-mysql", "las2peer-bootstrap"]
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-data-processing:develop
        environment:
            BOOTSTRAP: "las2peer-bootstrap:32010"
            LAS2PEER_ETH_HOST: "ethereum:8545"
            NODE_ID_SEED: "2"
            LAS2PEER_PORT: "32011"
            MYSQL_HOST: "mobsos-mysql"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "password"
            SEND_TO_LRS: "TRUE"
            WALLET: "1"
            SERVICE_EXTRA_ARGS: --observer
        ports:
            - "32011:32011"
            - "32011:32011/udp"
        volumes:
            - "las2peer-nodestorage:/app/las2peer/node-storage"
            - "./registry-config.properties:/src/etc/i5.las2peer.registry.data.RegistryConfiguration.properties"


    sbf-mysql:
        hostname: sbf-mysql
        networks:
            - las2peernet
        container_name: sbf-mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "SBF_MODELS"
            MYSQL_USER: "root"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306"
        volumes:
            - "sbf-mysql-data:/var/lib/mysql"

    rasa-nlu:
        hostname: rasa-nlu
        networks:
            - las2peernet
        container_name: rasa-nlu
        image: rasa/rasa:1.9.5-spacy-de
        command: ["/bin/sh", "-c", "rasa run --enable-api -m models"]
        ports:
            - "5005:5005"
        volumes:
            - "./rasa-models:/app/models"


    yjs:
        hostname: yjs
        networks:
            - las2peernet
        container_name: yjs
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/y-websockets-server:latest
        ports:
            - "1234:1234"
    
    sbf-frontend:
        hostname: sbf-frontend
        networks:
            - las2peernet
        container_name: sbf-frontend
        depends_on: ["yjs", "rasa-nlu", "sbf-manager"]
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/sbf-utils:develop
        environment:
            WEBHOST: "http://localhost:8071"
            YJS: "http://localhost:1234"
            OIDC_CLIENT_ID: "a7ece4a9-0a43-4fda-a33b-9c24a5a0d8f2"
            RASA_NLU: "http://rasa-nlu:5005"
            SBF_MANAGER: "http://localhost:32009/SBFManager"
            PORT: "8071"
        ports:
            - "8071:8071"

    sbf-manager:
        hostname: sbf-manager
        networks:
            - las2peernet
        container_name: sbf-manager
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/social-bot-manager:develop
        environment:
            LAS2PEER_PORT: "32014"
            BOOTSTRAP: "mobsos-data-processing:32011"
            #LAS2PEER_ETH_HOST: "ethereum:8545"
            #NODE_ID_SEED: "8"
            WALLET: "1"
            DATABASE_NAME: "SBF_MODELS"
            DATABASE_HOST: "sbf-mysql"
            DATABASE_PORT: "3306"
            DATABASE_USER: "root"
            DATABASE_PASSWORD: "password"
        ports:
            - "32014:32014"
            - "32014:32014/udp"
            - "32015:8080"
        volumes:
            - "./registry-config.properties:/src/etc/i5.las2peer.registry.data.RegistryConfiguration.properties"
        

volumes:
    ethdata:
    las2peer-nodestorage:
    mobsos-mysql-data:
    sbf-mysql-data: