version: "2.2"
networks: 
    las2peernet:

services:
    mobsos-mysql:
        hostname: mobsos-mysql
        networks:
            - las2peernet
        container_name: mobsos-mysql
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "LAS2PEERMON"
            MYSQL_ROOT_PASSWORD: "password"
        ports:
            - "3306:3306"
        volumes:
            - "mobsos-mysql-data:/var/lib/mysql"

    mobsos-data-processing:
        hostname: mobsos-data-processing
        networks:
            - las2peernet
        container_name: mobsos-data-processing
        depends_on: ["mobsos-mysql"]
        image: registry.tech4comp.dbis.rwth-aachen.de/rwthacis/mobsos-data-processing:develop
        environment:
            BOOTSTRAP: "las2peer-bootstrap:32010"
            LAS2PEER_ETH_HOST: "ethereum:8545"
            NODE_ID_SEED: "2"
            LAS2PEER_PORT: "32011"
            MYSQL_HOST: "mobsos-mysql"
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "password"
            SEND_TO_LRS: "TRUE"
            SEND_XAPI_TO_BOTS: "TRUE"
            WALLET: "1"
            #   SERVICE_EXTRA_ARGS: --observer
        ports:
            - "32011:32011"
            - "32011:32011/udp"
        volumes:
            - "las2peer-nodestorage:/app/las2peer/node-storage"
            - "./registry-config.properties:/src/etc/i5.las2peer.registry.data.RegistryConfiguration.properties"

volumes:
    las2peer-nodestorage:
    mobsos-mysql-data: