version: "2.2"
networks: 
    las2peernet:

services:
    pcs-mssql:
        hostname: pcs-mssql
        networks:
            - las2peernet
        container_name: pcs-mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        user: root
        environment:
            SA_PASSWORD: "privacyIS#1important!"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - mssql-data:/var/opt/mssql/data

    privacy-control-service:
        hostname: privacy-control-service
        networks:
            - las2peernet
        container_name: privacy-control-service
        depends_on: ["pcs-mssql"]
        image: pcs-local
        environment:
            BOOTSTRAP: "las2peer-bootstrap:32010"
            LAS2PEER_ETH_HOST: "ethereum:8545"
            NODE_ID_SEED: "12"
            LAS2PEER_PORT: "32016"
            WALLET: "1"
            OIDC_USER_INFO_ENDPOINT: "https://auth.las2peer.org/auth/realms/main/protocol/openid-connect/userinfo"
            FIRST_DPO_EMAIL: "jovanovic.boris@rwth-aachen.de"
            AUTHENTICATION_HEADER_NAME: "access_token"
            DB_URL: "postgresdb.tech4comp.dbis.rwth-aachen.de"
            DB_PORT: 5432
            DB_NAME: "test"
            DB_USERNAME: "tech4comp@tech4comp.de"
            DB_PASSWORD: "481ixX2Z5TjwxbpyynJZ"
            LAS2PEER_GET_SERVICES_ENDPOINT: "http://las2peer-bootstrap:8080/las2peer/getOtherNodesInfo"
            LRS_ACTOR_ACCOUNT_HOMEPAGE: "https://moodle.tech4comp.dbis.rwth-aachen.de/"
            LRS_STATEMENT_QUERY_ENDPOINT: "https://lrs.tech4comp.dbis.rwth-aachen.de/data/xAPI/statements"
            LRS_STATEMENT_DELETE_ENDPOINT: "https://lrs.tech4comp.dbis.rwth-aachen.de/api/v2/batchdelete/initialise"
            LRS_CLIENT_AUTHORISATION: "Basic YzQ1NWJkYzhjNTQ3NTUxYzJmZTNhZmRiM2IxYjlmNTExNzM2OTlhMTpjOGM0OGIxYWFkYjY0MmMzMmQ3ODk4OWNlNjI4NGJlOGIxN2ZhYWQ0"
        ports:
            - "32016:32016"
            - "32016:32016/udp"
        volumes:
            - "las2peer-nodestorage:/app/las2peer/node-storage"
            - "./registry-config.properties:/src/etc/i5.las2peer.registry.data.RegistryConfiguration.properties"

volumes:
    las2peer-nodestorage:
    mssql-data: