version: "3"
services:
  ethereum:
    image: rwthacis/monitored-geth-client
    ports:
      - 30303:30303/udp
      - 30303:30303/tcp
      - 8545:8545/tcp
      - 8546:8546/tcp
    environment:
      GETH_VERBOSITY: "3"
      ETHEREUM_DATA_DIR: /root/.ethereum/devchain
    volumes:
      - ethereumStoragePersistent:/root/.ethereum/devchain
    command: /root/start.sh
volumes:
  ethereumStoragePersistent: {}